### ISSUE TITLE
Resize image for promo

### ISSUE THREAD

**Issue by lisafast** [gc-proto/find-a-job#4]
@jmealing Can you resize the promo image on this page:
find-a-job/scenarioA/services/jobs/opportunities.html 
to be wider, as a single promo? I copied in the source code from the single promo you used on this page for health: 
https://gc-proto.github.io/health-1/validation/topics/immunization-vaccines.html

Thanks!

**Comment by jmealing** [comment]
Will do, can you let me know when you're done editing the page so we don't have a collision? I will also fix the most requested floating to the top on mobile at the same time.

**Comment by jmealing** [comment]
All fixed
